config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 50} 
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy, :show] 

  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end

  def edit

  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article successfully created"
      redirect_to @article
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def update
      if @article.update_attributes(article_params)
        flash[:success] = "Article was successfully updated"
        redirect_to @article
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  def destroy
    if @article.destroy
      flash[:success] = 'Article was successfully deleted.'
      redirect_to articles_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to articles_url
    end
  end

  def show
    
  end
  
  private
    def set_article
      @article = Article.find( params[:id] )
    end  

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<ul>
  <% @article.errors.full_messages.each.each do |msg| %>
    <li>
      <%= msg %>
    </li>
  <% end %>
</ul>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>  
  <p>
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to 'Show', article_path(@article) %> | 
  <%= link_to 'Back to article listing', articles_path %>
</p>

app/views/articles/edit.html.erb
<h1> Edit Selected Article </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles Listing </h1>
<p>
  <%= link_to 'Add New Article', new_article_path  %>
</p>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
    
  </tr>
  <% @articles.each do |article| %>    
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
    
  </tr>
 <% end %> 
</table>

app/views/articles/new.html.erb
<h1>Create Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1> Show Selected Article </h1>
<p>Title: <%= @article.title %> </p>
<p>Description: <%= @article.description %> </p>
<p>
  <%= link_to 'Edit', edit_article_path(@article) %> | 
  <%= link_to 'Back to article listing', articles_path %>
</p>

app/views/layouts/_messages.html.erb
<ul>
  <% flash.each do |name,msg| %>
    <li>      
      <%= msg %>      
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<%= link_to 'Home ', root_path %>

app/views/pages/home.html.erb
<h1>My Blog App Home</h1>
<%= link_to 'Alpha Blog', articles_path %> | <%= link_to 'About ', about_path %>